### ISSUE TITLE
cannot use lures

### ISSUE THREAD

**Issue by LennoxP90** [ohmcodes/WindowsGSM.TheFront#2]
After running my server using this plugin, creature lures no longer function

gives me the error: invaders unable to reach lure

also enemies completely ignore me when i get near them or attack them

this works fine if I run the server on its own.

**Comment by ohmcodes** [comment]
Pls submit an issue on their discorf its nothing to do with the plugin this is the only one having that kind of issue

**Comment by LennoxP90** [comment]
so i figured it out if you change the map setting in WindowsGSM to something other than DedicatedServer beacons break
this is because of this line
```csharp
string param =  $"ProjectWar_Start?{_serverData.ServerMap}?MaxPlayers={_serverData.ServerMaxPlayer}?udrs=steam -server -game -log -UserDir=\"{ServerPath.GetServersServerFiles(_serverData.ServerID)}\" {_serverData.ServerParam}";
```
the plugin uses what is placed in the GSM config

this could be resolved by hardcoding the plugin or educating on the ServerMap option requiring to be DedicatedServer

**Comment by ohmcodes** [comment]
> figured it out if you change the map setting in WindowsGSM to something other than DedicatedServer beacons break
> this is because of this line

Yes i note to my README that you shouldnt change that parameter
