### ISSUE TITLE
Sub-domain instead of IP

### ISSUE THREAD

**Issue by meinTS3** [ohmcodes/WindowsGSM.TheFront#3]
Why can't I use a sub-domain instead of the IP? (Example: s1.domain.com). Some servers have this.
A-Record is set, but server does not start.

Would it be possible to include this?

**Comment by ohmcodes** [comment]
> Why can't I use a sub-domain instead of the IP? (Example: s1.domain.com). Some servers have this. A-Record is set, but server does not start.
> 
> Would it be possible to include this?

The IP Address section on WGSM is for local network not for public IP for the router to find the appropriate machine where the server is installed
